#
# shib upgrade attribute-resolver playbook
# configured for idp-3.3
#

- hosts: "{{ target }}"
  serial: 1
  max_fail_percentage: 10
  gather_facts: false
  remote_user: iamidp
  vars:
    app_name: idp
    idp_base: /data/local
    idp_root: /data/local/idp-3.3

  tasks:

  - name: copy attribute-resolver config
    copy: "src={{idp_root}}/conf/attribute-resolver.xml dest={{idp_root}}/conf group=iam-dev mode=644"
    notify: ar_reload
    
  - name: copy attribute-resolver reloader
    copy: "src={{idp_root}}/local-bin/reload_attributeresolver dest={{idp_root}}/local-bin group=iam-dev mode=755"
    
  # 
  handlers:

  - name: ar_reload
    command: /usr/bin/nohup /data/local/idp-3.3/local-bin/reload_attributeresolver
    ignore_errors: no


