#
# shib idp warfile install playbook
# NOTE: configured for /data/local/idp symlink
#

- hosts: "{{ target }}"
  serial: 1
  max_fail_percentage: 10
  gather_facts: false
  remote_user: iamidp
  vars:
    app_name: idp
    idp_base: /data/local
    idp_root: /data/local/idp
    install_base: /data/webapps
    dev_name: idp-dev.u.washington.edu

  tasks:

  - name: copy idp.war
    copy: "src={{idp_root}}/war/idp.war dest={{idp_root}}/war group=iam-dev mode=644"
    register: warfile
    
  - name: unpack idp.war
    shell: "rm -rf /data/webapps/idp/*; cd /data/webapps/idp; jar xf {{idp_root}}/war/idp.war" 
    when: warfile.changed
    notify:
      - restart tomcat

  # run the handlers
  - meta: flush_handlers

  # 
  handlers:

   # restart tomcat
   - name: restart tomcat
     # command: /usr/bin/nohup /data/local/bin/ansible_command tomcat restart
     # command: /usr/bin/nohup systemctl restart tomcat
     become: yes
     service: name=tomcat enabled=yes state=restarted
     notify: wait for tomcat

   # wait for tomcat to restart
   - name: wait for tomcat
     shell: "c=0;while [ $c -lt 20 ]; do wget -O /dev/null -q  http://localhost/tomcatmanager/text/serverinfo;[ $? -eq 0 ] && exit 0;let c=c+1;sleep 5; done;exit 1"
     register: wait_result
     failed_when: "wait_result.rc != 0"
