#
# shib upgrade attribute-resolver playbook
# configured for idp-4.1
#

- hosts: "{{ target }}"
  serial: 1
  max_fail_percentage: 10
  gather_facts: false
  remote_user: iamidp
  vars:
    app_name: idp
    idp_base: /data/local
    idp_root: /data/local/idp-4.1

  tasks:

  - name: jinja2 copy cluster-specific files
    template: "src={{idp_root}}{{item}}.tmpl dest={{idp_root}}{{item}} group=iam-dev mode=644"
    with_items:
       - /conf/attribute-resolver.xml
    notify: ar_reload
    
  - name: copy attribute-resolver reloader
    copy: "src={{idp_root}}/local-bin/reload_resolver dest={{idp_root}}/local-bin group=iam-dev mode=755"
    
  # 
  handlers:

  - name: ar_reload
    command: /usr/bin/nohup /data/local/idp-4.1/local-bin/reload_resolver
    ignore_errors: no


