#
# shib upgrade for MQD playbook
# configured for idp-4.1
#

- hosts: "{{ target }}"
  serial: 1
  max_fail_percentage: 10
  gather_facts: false
  remote_user: iamidp
  vars:
    app_name: idp
    idp_base: /data/local
    idp_root: /data/local/idp-4.1

  tasks:

  - name: copy incommon cerds
    copy: "src={{idp_root}}/credentials/inc-md-cert-mdq.pem dest={{idp_root}}/credentials group=iam-dev mode=644"

  - name: copy metadata provider
    copy: "src={{idp_root}}/conf/metadata-providers.xml dest={{idp_root}}/conf group=iam-dev mode=644"
    notify: mdq_reload
    
  handlers:

  - name: mdq_reload
    command: /usr/bin/nohup /data/local/idp-4.1/local-bin/reload_metadata
    ignore_errors: no


